# Generated by Django 5.2.10 on 2026-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaladdictionassessment',
            name='risk_confidence',
            field=models.FloatField(blank=True, help_text='Prediction probability from ML model', null=True),
        ),
    ]
