# Generated by Django 5.2.10 on 2026-02-09 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_digitaladdictionassessment_risk_confidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaladdictionassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da2',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da3',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da4',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da5',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da6',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da7',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='da8',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='gaming_time',
            field=models.CharField(choices=[('None', 'None'), ('<30m', '<30m'), ('30–60m', '30–60m'), ('1–2h', '1–2h'), ('>2h', '>2h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='mobile_data',
            field=models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='night_phone_use',
            field=models.CharField(choices=[('Never', 'Never'), ('<30m', '<30m'), ('30–60m', '30–60m'), ('1–2h', '1–2h'), ('>2h', '>2h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='notif_per_hour',
            field=models.CharField(choices=[('<5 times', '<5 times'), ('5–10 times', '5–10 times'), ('11–20 times', '11–20 times'), ('>20 times', '>20 times')], max_length=15),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='own_smartphone',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='predicted_risk',
            field=models.CharField(blank=True, choices=[('not_at_risk', 'Not at risk'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='primary_device',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='risk_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='screen_weekdays',
            field=models.CharField(choices=[('<2h', '<2h'), ('2–3h', '2–3h'), ('3–4h', '3–4h'), ('4–6h', '4–6h'), ('>6h', '>6h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='screen_weekends',
            field=models.CharField(choices=[('<2h', '<2h'), ('2–3h', '2–3h'), ('3–4h', '3–4h'), ('4–6h', '4–6h'), ('>6h', '>6h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='self_rated_da',
            field=models.CharField(choices=[('not_at_risk', 'Not at risk'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='social_time',
            field=models.CharField(choices=[('<1h', '<1h'), ('1–2h', '1–2h'), ('2–3h', '2–3h'), ('3–4h', '3–4h'), ('>4h', '>4h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='digitaladdictionassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
